branches:
  only:
    - master

sudo: required

language: go

services:
    - docker

before_install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega

# For now, when TravisCI runs we want it to run all available tests via ginkgo.
# Also, have ginkgo return coverage reports for each package.
script:
  - make build

# after_success:
#   -
